### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by andersonkyle** [juiser/juiser#3]
In order for this library to be easily consumed, it would be great if it were accessible via Maven Central.

**Comment by lhazlewood** [comment]
Hi @andersonkyle !  I'm surprised anyone is using this since we didn't announce it yet! ;)  That said, thanks for opening this issue - we do indeed need to publish it to Maven Central.

**Comment by andersonkyle** [comment]
@lhazlewood Yeah, Micah recommended it since I was having trouble securing backend microservices when auth is handled at the gateway.

**Comment by mraible** [comment]
@andersonkyle Your wish has been granted! 

https://github.com/juiser/juiser/releases/tag/v1.0.0
https://repo.maven.apache.org/maven2/org/juiser
